version: "3.9"

services:
  takeout_api:
    container_name: takeout_api
    entrypoint: ./.docker/go/entrypoint.sh
    build: ./.docker/go
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
    networks:
      - takeout-app-net
    depends_on:
      - takeout_db
  takeout_db:
    container_name: takeout_db
    image: mongo:4.4.10-rc0-focal
    ports:
      - "27017:27017"
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - takeout-app-net
networks:
  takeout-app-net:
    driver: bridge